name: blindtestlol_flutter_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flare_flutter: ^3.0.2
  image: ^4.1.7
  video_player: ^2.8.6
  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/song/
    - assets/images/
    - assets/images/legendes/